import type {App} from 'vue'
import {
    create,
    NForm,
    NFormItem,
    NInputNumber,
    NButton,
    NInput,
    NSelect,
    NRadio,
    NRadioGroup,
    NCheckbox,
    NRadioButton,
    NCheckboxGroup,
    NPopover,
    NDropdown,
    NMenu,
    NTooltip,
    NDivider,
    NTab,
    NTabs,
    NConfigProvider,
    NTabPane,
    NEmpty,
    NGradientText,
    NIcon,
    NModal,
    NSpace,
    NMessageProvider,
    NLoadingBarProvider,
    NNotificationProvider,
    NScrollbar,
    NAlert,
    NText,
    NEllipsis,
    NInputGroup,
    NTree,
    NSpin,
    NCard,
    NCode,
    NTag,
    NButtonGroup,
    NSkeleton,
    NLog,
    NDynamicInput,
    NDataTable,
    NPopconfirm,
    NStatistic,
    NSwitch,
    NGlobalStyle,
    NGi,
    NGrid,
} from "naive-ui";


// https://www.naiveui.com/en-US/os-theme/docs/import-on-demand
const naive = create({
    components: [
        NForm,
        NFormItem,
        NInputNumber,
        NButton,
        NInput,
        NSelect,
        NRadio,
        NRadioGroup,
        NCheckbox,
        NRadioButton,
        NCheckboxGroup,
        NPopover,
        NDropdown,
        NMenu,
        NTooltip,
        NDivider,
        NTab,
        NTabs,
        NConfigProvider,
        NTabPane,
        NEmpty,
        NGradientText,
        NIcon,
        NModal,
        NSpace,
        NMessageProvider,
        NLoadingBarProvider,
        NNotificationProvider,
        NScrollbar,
        NAlert,
        NText,
        NEllipsis,
        NInputGroup,
        NTree,
        NSpin,
        NCard,
        NCode,
        NTag,
        NButtonGroup,
        NSkeleton,
        NLog,
        NDynamicInput,
        NDataTable,
        NPopconfirm,
        NStatistic,
        NSwitch,
        NGlobalStyle,
        NGi,
        NGrid,
    ]
})


export function setupNaive(app: App<Element>) {
    app.use(naive)
}